### ISSUE TITLE
RFE: Support installing a local RPM from the command line

### ISSUE THREAD

**Issue by kkofler** [manatools/dnfdragora#15]
Please add support for installing a local RPM file passed on the command line, looking in the repositories for any missing dependencies, together with a file association for RPM files. That allows installing an RPM from a browser (e.g., the `*-release` RPM that configures a repository, to bootstrap a repository) without going through the CLI. (This is one of the features Apper had that dnfdragora is still missing.)

The required dnfdaemon support should already be there, because `yumex-dnf -I /path/to/some.rpm` works. As far as I can tell, you just have to pass the full path to the file instead of a package name to the dnf(daemon) install command.

Note that unlike yumex-dnf, I would suggest just treating any non-option argument as an RPM file (`dnfdragora /path/to/some.rpm`) instead of requiring `-I`, it makes the file association simpler.

**Comment by Conan-Kudo** [comment]
I'd prefer to see us use subcommands or parameters, rather than making that assumption.

**Comment by Conan-Kudo** [comment]
(Note, [Yumex-DNF code for this](https://github.com/timlau/yumex-dnf/blob/develop/src/yumex/__init__.py#L1162))

**Comment by kkofler** [comment]
The reason I suggest accepting the files on the command line directly, with no other parameter, is that that allows having the normal `dnfdragora.desktop` claim the RPM MIME type. You may want to add a `%F` to the Exec= line (which is ignored if you run it from the menu), but IIRC that is the default anyway.

If you require a special parameter in front of the files, you need a separate `dnfdragora-localinstall.desktop` to handle the MIME type.

**Comment by Conan-Kudo** [comment]
In that case, we might want to support that mode as well. The switches would be necessary for supporting modes other than install (such as forcing upgrade or doing removal).

**Comment by anaselli** [comment]
It should be fixed now, do you think it is needed also for removing? Because i can see a package selection with the intent to install it by clicking or double clicking on it... but does removal make sense?

**Comment by kkofler** [comment]
The `.desktop` file part is still missing though. And as I explained in my previous comment, implementing that part would be easier if the code took RPM files to install directly, without an `--install` switch (as, e.g., Apper is doing), because then you could just have the normal `dnfdragora.desktop` accept RPMs. That is not possible if the switch is required, because if you try to run a `.desktop` file with `Exec=dnfdragora --install %F` from the menu, it will only ignore the `%F` and try to run `dnfdragora --install`, which will of course fail. So, in that case, you need a separate `.desktop` file.

Apper's command line works the way I am suggesting:
```
Usage: apper [options] [package]
Apper is an application to get and manage software

Options:
  -v, --version              Displays version information.
  -h, --help                 Displays this help.
  --updates                  Show updates
  --settings                 Show settings
  --backend-details          Show backend details
  --type <mime-type>         Mime type installer
  --name <name>              Package name installer
  --file <file>              Single file installer
  --resource <lang>          Font resource installer
  --catalog <file>           Catalog installer
  --author                   Show author information.
  --license                  Show license information.
  --desktopfile <file name>  The base file name of the desktop entry for this
                             application.

Arguments:
  [package]                  Package file to install
```
but interestingly, package installation is done by a separate `org.kde.apper_installer.desktop` for some reason that is not clear to me.

Yumex-DNF does things your way:
```
usage: app [-h] [-d] [-y] [--exit] [-I PACKAGE] [-R PACKAGE] [--updateall]

optional arguments:
  -h, --help            show this help message and exit
  -d, --debug
  -y, --yes             Answer yes/ok to all questions
  --exit                tell dnfdaemon dbus services used by yumex to exit
  -I PACKAGE, --install PACKAGE
                        Install Package
  -R PACKAGE, --remove PACKAGE
                        Remove Package
  --updateall           apply all available updates
```
and includes a dedicated `yumex-dnf-local.desktop` to support installation of local RPMs.

Either of the 2 solutions should be implemented:

* add a `dnfdragora-local.desktop` modeled after `yumex-dnf-local.desktop`, or
* accept RPMs on the command line without a switch and adjust `dnfdragora.desktop` to claim the MIME type.

Either way, there should be a `.desktop` file with
```
MimeType=application/x-rpm;application/x-redhat-package-manager;
```
(and the `Exec=` line should end in `%F`).

**Comment by anaselli** [comment]
Yes you are right, i will add a desktop file for it asap, but we need to add also localization for them, maybe later.

**Comment by Conan-Kudo** [comment]
@anaselli I've already got a desktop file to commit. I'll adjust everything to install one. :)

**Comment by Conan-Kudo** [comment]
Should be fixed by 3cd1ed28922adf979103c54658c237f27de7d0e3 now.
